name: Master deployment

on:
  push:
    paths:
      - 'i18n/**'
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: INSTALL
        run: rm -rf node_modules && yarn install --immutable --immutable-cache --check-cache

      # Build each locale separately
      - name: Build locales
        run: |
          for locale in en ko de es fr it ja pt br hi id ru th tl
          do
            yarn build --locale $locale
          done

      # Merge all the locales into one build
      - name: Merge locales
        run: |
          mkdir -p build/merged
          for locale in en ko de es fr it ja pt br hi id ru th tl
          do
            cp -R build/$locale/. build/merged
          done

      # Upload the merged build to S3 bucket
      - name: Upload to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.POLYGON_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.POLYGON_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.POLYGON_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'build/merged'

      - name: Invalidate CloudFront distribution and wait for completion
        uses: muratiger/invalidate-cloudfront-and-wait-for-completion-action@master
        env:
          DISTRIBUTION_ID: ${{ secrets.POLYGON_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.POLYGON_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.POLYGON_AWS_SECRET_ACCESS_KEY }}
